// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msg_id.proto
// Protobuf Java Version: 4.34.0

package com.muyi.proto;

/**
 * <pre>
 * *
 * 全局消息 ID 枚举（自动生成）
 *
 * 号段分配：
 * 1001-1999  玩家基础（登录、角色）
 * 2001-2999  玩家信息/背包/装备
 * 3001-3999  战斗
 * 4001-4999  联盟
 * 5001-5999  世界/地图
 * 9001-9999  Gate 内部协议
 * </pre>
 *
 * Protobuf enum {@code MsgId}
 */
@com.google.protobuf.Generated
public enum MsgId
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>MSG_ID_UNSPECIFIED = 0;</code>
   */
  MSG_ID_UNSPECIFIED(0),
  /**
   * <pre>
   * ==================== 玩家基础（登录、角色） 1001-1999 ====================
   * </pre>
   *
   * <code>PLAYER_LOGIN_REQ = 1001;</code>
   */
  PLAYER_LOGIN_REQ(1001),
  /**
   * <code>PLAYER_LOGIN_RESP = 1002;</code>
   */
  PLAYER_LOGIN_RESP(1002),
  /**
   * <pre>
   * ==================== 玩家信息/背包/装备 2001-2999 ====================
   * </pre>
   *
   * <code>PLAYER_INFO_REQ = 2001;</code>
   */
  PLAYER_INFO_REQ(2001),
  /**
   * <code>PLAYER_INFO_RESP = 2002;</code>
   */
  PLAYER_INFO_RESP(2002),
  /**
   * <pre>
   * ==================== Gate 内部协议 9001-9999 ====================
   * </pre>
   *
   * <code>GATE_AUTH_REQ = 9001;</code>
   */
  GATE_AUTH_REQ(9001),
  /**
   * <code>GATE_AUTH_RESP = 9002;</code>
   */
  GATE_AUTH_RESP(9002),
  /**
   * <code>GATE_HEARTBEAT_REQ = 9003;</code>
   */
  GATE_HEARTBEAT_REQ(9003),
  /**
   * <code>GATE_HEARTBEAT_RESP = 9004;</code>
   */
  GATE_HEARTBEAT_RESP(9004),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "MsgId");
  }
  /**
   * <code>MSG_ID_UNSPECIFIED = 0;</code>
   */
  public static final int MSG_ID_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * ==================== 玩家基础（登录、角色） 1001-1999 ====================
   * </pre>
   *
   * <code>PLAYER_LOGIN_REQ = 1001;</code>
   */
  public static final int PLAYER_LOGIN_REQ_VALUE = 1001;
  /**
   * <code>PLAYER_LOGIN_RESP = 1002;</code>
   */
  public static final int PLAYER_LOGIN_RESP_VALUE = 1002;
  /**
   * <pre>
   * ==================== 玩家信息/背包/装备 2001-2999 ====================
   * </pre>
   *
   * <code>PLAYER_INFO_REQ = 2001;</code>
   */
  public static final int PLAYER_INFO_REQ_VALUE = 2001;
  /**
   * <code>PLAYER_INFO_RESP = 2002;</code>
   */
  public static final int PLAYER_INFO_RESP_VALUE = 2002;
  /**
   * <pre>
   * ==================== Gate 内部协议 9001-9999 ====================
   * </pre>
   *
   * <code>GATE_AUTH_REQ = 9001;</code>
   */
  public static final int GATE_AUTH_REQ_VALUE = 9001;
  /**
   * <code>GATE_AUTH_RESP = 9002;</code>
   */
  public static final int GATE_AUTH_RESP_VALUE = 9002;
  /**
   * <code>GATE_HEARTBEAT_REQ = 9003;</code>
   */
  public static final int GATE_HEARTBEAT_REQ_VALUE = 9003;
  /**
   * <code>GATE_HEARTBEAT_RESP = 9004;</code>
   */
  public static final int GATE_HEARTBEAT_RESP_VALUE = 9004;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MsgId valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MsgId forNumber(int value) {
    switch (value) {
      case 0: return MSG_ID_UNSPECIFIED;
      case 1001: return PLAYER_LOGIN_REQ;
      case 1002: return PLAYER_LOGIN_RESP;
      case 2001: return PLAYER_INFO_REQ;
      case 2002: return PLAYER_INFO_RESP;
      case 9001: return GATE_AUTH_REQ;
      case 9002: return GATE_AUTH_RESP;
      case 9003: return GATE_HEARTBEAT_REQ;
      case 9004: return GATE_HEARTBEAT_RESP;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MsgId>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MsgId> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MsgId>() {
          public MsgId findValueByNumber(int number) {
            return MsgId.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.muyi.proto.MsgIdOuterClass.getDescriptor().getEnumType(0);
  }

  private static final MsgId[] VALUES = values();

  public static MsgId valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MsgId(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:MsgId)
}

