// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gate.proto
// Protobuf Java Version: 4.34.0

package com.muyi.proto.gate;

@com.google.protobuf.Generated
public final class Gate extends com.google.protobuf.GeneratedFile {
  private Gate() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "Gate");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GateAuthReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GateAuthReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GateAuthResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GateAuthResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GateHeartbeatReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GateHeartbeatReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GateHeartbeatResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GateHeartbeatResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngate.proto\032\roptions.proto\"#\n\013GateAuthR" +
      "eq\022\r\n\005token\030\001 \001(\t:\005\210\303\032\251F\"X\n\014GateAuthResp" +
      "\022\017\n\007success\030\001 \001(\010\022\013\n\003uid\030\002 \001(\003\022\017\n\007messag" +
      "e\030\003 \001(\t\022\022\n\nencryptKey\030\004 \001(\014:\005\210\303\032\252F\"\031\n\020Ga" +
      "teHeartbeatReq:\005\210\303\032\253F\".\n\021GateHeartbeatRe" +
      "sp\022\022\n\nserverTime\030\001 \001(\003:\005\210\303\032\254FB\027\n\023com.muy" +
      "i.proto.gateP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.muyi.proto.MsgOptions.getDescriptor(),
        });
    internal_static_GateAuthReq_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_GateAuthReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GateAuthReq_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_GateAuthResp_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_GateAuthResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GateAuthResp_descriptor,
        new java.lang.String[] { "Success", "Uid", "Message", "EncryptKey", });
    internal_static_GateHeartbeatReq_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_GateHeartbeatReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GateHeartbeatReq_descriptor,
        new java.lang.String[] { });
    internal_static_GateHeartbeatResp_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_GateHeartbeatResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GateHeartbeatResp_descriptor,
        new java.lang.String[] { "ServerTime", });
    descriptor.resolveAllFeaturesImmutable();
    com.muyi.proto.MsgOptions.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.muyi.proto.MsgOptions.msgId);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
