// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gate.proto
// Protobuf Java Version: 4.34.0

package com.muyi.proto.gate;

@com.google.protobuf.Generated
public interface GateAuthReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GateAuthReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
