// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gate.proto
// Protobuf Java Version: 4.34.0

package com.muyi.proto.gate;

@com.google.protobuf.Generated
public interface GateHeartbeatReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GateHeartbeatReq)
    com.google.protobuf.MessageOrBuilder {
}
