// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gate.proto
// Protobuf Java Version: 4.34.0

package com.muyi.proto.gate;

@com.google.protobuf.Generated
public interface GateHeartbeatRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GateHeartbeatResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 serverTime = 1;</code>
   * @return The serverTime.
   */
  long getServerTime();
}
