// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gate.proto
// Protobuf Java Version: 4.34.0

package com.muyi.proto.gate;

@com.google.protobuf.Generated
public interface GateAuthRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GateAuthResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>int64 uid = 2;</code>
   * @return The uid.
   */
  long getUid();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * RC4 master key, 认证成功后客户端用此密钥初始化加密
   * </pre>
   *
   * <code>bytes encryptKey = 4;</code>
   * @return The encryptKey.
   */
  com.google.protobuf.ByteString getEncryptKey();
}
