// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game.proto
// Protobuf Java Version: 4.34.0

package com.muyi.proto.game;

@com.google.protobuf.Generated
public interface EnterWorldRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnterWorldResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 0=成功
   * </pre>
   *
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 分配的 world 服务器 ID
   * </pre>
   *
   * <code>int32 worldServerId = 3;</code>
   * @return The worldServerId.
   */
  int getWorldServerId();
}
