// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game.proto
// Protobuf Java Version: 4.34.0

package com.muyi.proto.game;

@com.google.protobuf.Generated
public final class Game extends com.google.protobuf.GeneratedFile {
  private Game() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "Game");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerLoginReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerLoginReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerLoginResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerLoginResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerInfoReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerInfoReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerInfoResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerInfoResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngame.proto\032\roptions.proto\"\027\n\016PlayerLog" +
      "inReq:\005\210\303\032\351\007\"X\n\017PlayerLoginResp\022\014\n\004code\030" +
      "\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\037\n\nplayerData\030\003 \001" +
      "(\0132\013.PlayerData:\005\210\303\032\352\007\"\237\001\n\nPlayerData\022\013\n" +
      "\003uid\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\r\n\005level\030\003 \001(\005\022" +
      "\013\n\003exp\030\004 \001(\003\022\020\n\010vipLevel\030\005 \001(\005\022\014\n\004gold\030\006" +
      " \001(\003\022\017\n\007diamond\030\007 \001(\003\022\025\n\rlastLoginTime\030\010" +
      " \001(\003\022\022\n\ncreateTime\030\t \001(\003\"\026\n\rPlayerInfoRe" +
      "q:\005\210\303\032\321\017\"A\n\016PlayerInfoResp\022\013\n\003uid\030\001 \001(\003\022" +
      "\014\n\004name\030\002 \001(\t\022\r\n\005level\030\003 \001(\005:\005\210\303\032\322\017B\027\n\023c" +
      "om.muyi.proto.gameP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.muyi.proto.MsgOptions.getDescriptor(),
        });
    internal_static_PlayerLoginReq_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_PlayerLoginReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PlayerLoginReq_descriptor,
        new java.lang.String[] { });
    internal_static_PlayerLoginResp_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_PlayerLoginResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PlayerLoginResp_descriptor,
        new java.lang.String[] { "Code", "Message", "PlayerData", });
    internal_static_PlayerData_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_PlayerData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PlayerData_descriptor,
        new java.lang.String[] { "Uid", "Name", "Level", "Exp", "VipLevel", "Gold", "Diamond", "LastLoginTime", "CreateTime", });
    internal_static_PlayerInfoReq_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_PlayerInfoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PlayerInfoReq_descriptor,
        new java.lang.String[] { });
    internal_static_PlayerInfoResp_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_PlayerInfoResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PlayerInfoResp_descriptor,
        new java.lang.String[] { "Uid", "Name", "Level", });
    descriptor.resolveAllFeaturesImmutable();
    com.muyi.proto.MsgOptions.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.muyi.proto.MsgOptions.msgId);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
