// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game.proto
// Protobuf Java Version: 4.34.0

package com.muyi.proto.game;

@com.google.protobuf.Generated
public interface PlayerLoginRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PlayerLoginResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 0=成功
   * </pre>
   *
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.PlayerData playerData = 3;</code>
   * @return Whether the playerData field is set.
   */
  boolean hasPlayerData();
  /**
   * <code>.PlayerData playerData = 3;</code>
   * @return The playerData.
   */
  com.muyi.proto.game.PlayerData getPlayerData();
  /**
   * <code>.PlayerData playerData = 3;</code>
   */
  com.muyi.proto.game.PlayerDataOrBuilder getPlayerDataOrBuilder();
}
