// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game.proto
// Protobuf Java Version: 4.34.0

package com.muyi.proto.game;

@com.google.protobuf.Generated
public interface PlayerDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PlayerData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 uid = 1;</code>
   * @return The uid.
   */
  long getUid();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 level = 3;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <code>int64 exp = 4;</code>
   * @return The exp.
   */
  long getExp();

  /**
   * <code>int32 vipLevel = 5;</code>
   * @return The vipLevel.
   */
  int getVipLevel();

  /**
   * <code>int64 gold = 6;</code>
   * @return The gold.
   */
  long getGold();

  /**
   * <code>int64 diamond = 7;</code>
   * @return The diamond.
   */
  long getDiamond();

  /**
   * <code>int64 lastLoginTime = 8;</code>
   * @return The lastLoginTime.
   */
  long getLastLoginTime();

  /**
   * <code>int64 createTime = 9;</code>
   * @return The createTime.
   */
  long getCreateTime();
}
