// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game.proto
// Protobuf Java Version: 4.34.0

package com.muyi.proto.game;

/**
 * Protobuf type {@code PlayerData}
 */
@com.google.protobuf.Generated
public final class PlayerData extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PlayerData)
    PlayerDataOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "PlayerData");
  }
  // Use PlayerData.newBuilder() to construct.
  private PlayerData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PlayerData() {
    name_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.muyi.proto.game.Game.internal_static_PlayerData_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.muyi.proto.game.Game.internal_static_PlayerData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.muyi.proto.game.Game.internal_static_PlayerData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.muyi.proto.game.PlayerData.class, com.muyi.proto.game.PlayerData.Builder.class);
  }

  public static final int UID_FIELD_NUMBER = 1;
  private long uid_ = 0L;
  /**
   * <code>int64 uid = 1;</code>
   * @return The uid.
   */
  @java.lang.Override
  public long getUid() {
    return uid_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LEVEL_FIELD_NUMBER = 3;
  private int level_ = 0;
  /**
   * <code>int32 level = 3;</code>
   * @return The level.
   */
  @java.lang.Override
  public int getLevel() {
    return level_;
  }

  public static final int EXP_FIELD_NUMBER = 4;
  private long exp_ = 0L;
  /**
   * <code>int64 exp = 4;</code>
   * @return The exp.
   */
  @java.lang.Override
  public long getExp() {
    return exp_;
  }

  public static final int VIPLEVEL_FIELD_NUMBER = 5;
  private int vipLevel_ = 0;
  /**
   * <code>int32 vipLevel = 5;</code>
   * @return The vipLevel.
   */
  @java.lang.Override
  public int getVipLevel() {
    return vipLevel_;
  }

  public static final int GOLD_FIELD_NUMBER = 6;
  private long gold_ = 0L;
  /**
   * <code>int64 gold = 6;</code>
   * @return The gold.
   */
  @java.lang.Override
  public long getGold() {
    return gold_;
  }

  public static final int DIAMOND_FIELD_NUMBER = 7;
  private long diamond_ = 0L;
  /**
   * <code>int64 diamond = 7;</code>
   * @return The diamond.
   */
  @java.lang.Override
  public long getDiamond() {
    return diamond_;
  }

  public static final int LASTLOGINTIME_FIELD_NUMBER = 8;
  private long lastLoginTime_ = 0L;
  /**
   * <code>int64 lastLoginTime = 8;</code>
   * @return The lastLoginTime.
   */
  @java.lang.Override
  public long getLastLoginTime() {
    return lastLoginTime_;
  }

  public static final int CREATETIME_FIELD_NUMBER = 9;
  private long createTime_ = 0L;
  /**
   * <code>int64 createTime = 9;</code>
   * @return The createTime.
   */
  @java.lang.Override
  public long getCreateTime() {
    return createTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (uid_ != 0L) {
      output.writeInt64(1, uid_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
    }
    if (level_ != 0) {
      output.writeInt32(3, level_);
    }
    if (exp_ != 0L) {
      output.writeInt64(4, exp_);
    }
    if (vipLevel_ != 0) {
      output.writeInt32(5, vipLevel_);
    }
    if (gold_ != 0L) {
      output.writeInt64(6, gold_);
    }
    if (diamond_ != 0L) {
      output.writeInt64(7, diamond_);
    }
    if (lastLoginTime_ != 0L) {
      output.writeInt64(8, lastLoginTime_);
    }
    if (createTime_ != 0L) {
      output.writeInt64(9, createTime_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (uid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, uid_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
    }
    if (level_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, level_);
    }
    if (exp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, exp_);
    }
    if (vipLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, vipLevel_);
    }
    if (gold_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, gold_);
    }
    if (diamond_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, diamond_);
    }
    if (lastLoginTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, lastLoginTime_);
    }
    if (createTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, createTime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.muyi.proto.game.PlayerData)) {
      return super.equals(obj);
    }
    com.muyi.proto.game.PlayerData other = (com.muyi.proto.game.PlayerData) obj;

    if (getUid()
        != other.getUid()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (getLevel()
        != other.getLevel()) return false;
    if (getExp()
        != other.getExp()) return false;
    if (getVipLevel()
        != other.getVipLevel()) return false;
    if (getGold()
        != other.getGold()) return false;
    if (getDiamond()
        != other.getDiamond()) return false;
    if (getLastLoginTime()
        != other.getLastLoginTime()) return false;
    if (getCreateTime()
        != other.getCreateTime()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUid());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getLevel();
    hash = (37 * hash) + EXP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExp());
    hash = (37 * hash) + VIPLEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getVipLevel();
    hash = (37 * hash) + GOLD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGold());
    hash = (37 * hash) + DIAMOND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDiamond());
    hash = (37 * hash) + LASTLOGINTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastLoginTime());
    hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreateTime());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.muyi.proto.game.PlayerData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.muyi.proto.game.PlayerData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.muyi.proto.game.PlayerData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.muyi.proto.game.PlayerData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.muyi.proto.game.PlayerData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.muyi.proto.game.PlayerData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.muyi.proto.game.PlayerData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.muyi.proto.game.PlayerData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.muyi.proto.game.PlayerData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.muyi.proto.game.PlayerData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.muyi.proto.game.PlayerData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.muyi.proto.game.PlayerData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.muyi.proto.game.PlayerData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PlayerData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PlayerData)
      com.muyi.proto.game.PlayerDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.muyi.proto.game.Game.internal_static_PlayerData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.muyi.proto.game.Game.internal_static_PlayerData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.muyi.proto.game.PlayerData.class, com.muyi.proto.game.PlayerData.Builder.class);
    }

    // Construct using com.muyi.proto.game.PlayerData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      uid_ = 0L;
      name_ = "";
      level_ = 0;
      exp_ = 0L;
      vipLevel_ = 0;
      gold_ = 0L;
      diamond_ = 0L;
      lastLoginTime_ = 0L;
      createTime_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.muyi.proto.game.Game.internal_static_PlayerData_descriptor;
    }

    @java.lang.Override
    public com.muyi.proto.game.PlayerData getDefaultInstanceForType() {
      return com.muyi.proto.game.PlayerData.getDefaultInstance();
    }

    @java.lang.Override
    public com.muyi.proto.game.PlayerData build() {
      com.muyi.proto.game.PlayerData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.muyi.proto.game.PlayerData buildPartial() {
      com.muyi.proto.game.PlayerData result = new com.muyi.proto.game.PlayerData(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.muyi.proto.game.PlayerData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.uid_ = uid_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.level_ = level_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.exp_ = exp_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.vipLevel_ = vipLevel_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.gold_ = gold_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.diamond_ = diamond_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.lastLoginTime_ = lastLoginTime_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.createTime_ = createTime_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.muyi.proto.game.PlayerData) {
        return mergeFrom((com.muyi.proto.game.PlayerData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.muyi.proto.game.PlayerData other) {
      if (other == com.muyi.proto.game.PlayerData.getDefaultInstance()) return this;
      if (other.getUid() != 0L) {
        setUid(other.getUid());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getLevel() != 0) {
        setLevel(other.getLevel());
      }
      if (other.getExp() != 0L) {
        setExp(other.getExp());
      }
      if (other.getVipLevel() != 0) {
        setVipLevel(other.getVipLevel());
      }
      if (other.getGold() != 0L) {
        setGold(other.getGold());
      }
      if (other.getDiamond() != 0L) {
        setDiamond(other.getDiamond());
      }
      if (other.getLastLoginTime() != 0L) {
        setLastLoginTime(other.getLastLoginTime());
      }
      if (other.getCreateTime() != 0L) {
        setCreateTime(other.getCreateTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              uid_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              level_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              exp_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              vipLevel_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              gold_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              diamond_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              lastLoginTime_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              createTime_ = input.readInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long uid_ ;
    /**
     * <code>int64 uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public long getUid() {
      return uid_;
    }
    /**
     * <code>int64 uid = 1;</code>
     * @param value The uid to set.
     * @return This builder for chaining.
     */
    public Builder setUid(long value) {

      uid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 uid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      uid_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int level_ ;
    /**
     * <code>int32 level = 3;</code>
     * @return The level.
     */
    @java.lang.Override
    public int getLevel() {
      return level_;
    }
    /**
     * <code>int32 level = 3;</code>
     * @param value The level to set.
     * @return This builder for chaining.
     */
    public Builder setLevel(int value) {

      level_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 level = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLevel() {
      bitField0_ = (bitField0_ & ~0x00000004);
      level_ = 0;
      onChanged();
      return this;
    }

    private long exp_ ;
    /**
     * <code>int64 exp = 4;</code>
     * @return The exp.
     */
    @java.lang.Override
    public long getExp() {
      return exp_;
    }
    /**
     * <code>int64 exp = 4;</code>
     * @param value The exp to set.
     * @return This builder for chaining.
     */
    public Builder setExp(long value) {

      exp_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 exp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearExp() {
      bitField0_ = (bitField0_ & ~0x00000008);
      exp_ = 0L;
      onChanged();
      return this;
    }

    private int vipLevel_ ;
    /**
     * <code>int32 vipLevel = 5;</code>
     * @return The vipLevel.
     */
    @java.lang.Override
    public int getVipLevel() {
      return vipLevel_;
    }
    /**
     * <code>int32 vipLevel = 5;</code>
     * @param value The vipLevel to set.
     * @return This builder for chaining.
     */
    public Builder setVipLevel(int value) {

      vipLevel_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 vipLevel = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearVipLevel() {
      bitField0_ = (bitField0_ & ~0x00000010);
      vipLevel_ = 0;
      onChanged();
      return this;
    }

    private long gold_ ;
    /**
     * <code>int64 gold = 6;</code>
     * @return The gold.
     */
    @java.lang.Override
    public long getGold() {
      return gold_;
    }
    /**
     * <code>int64 gold = 6;</code>
     * @param value The gold to set.
     * @return This builder for chaining.
     */
    public Builder setGold(long value) {

      gold_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 gold = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearGold() {
      bitField0_ = (bitField0_ & ~0x00000020);
      gold_ = 0L;
      onChanged();
      return this;
    }

    private long diamond_ ;
    /**
     * <code>int64 diamond = 7;</code>
     * @return The diamond.
     */
    @java.lang.Override
    public long getDiamond() {
      return diamond_;
    }
    /**
     * <code>int64 diamond = 7;</code>
     * @param value The diamond to set.
     * @return This builder for chaining.
     */
    public Builder setDiamond(long value) {

      diamond_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 diamond = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDiamond() {
      bitField0_ = (bitField0_ & ~0x00000040);
      diamond_ = 0L;
      onChanged();
      return this;
    }

    private long lastLoginTime_ ;
    /**
     * <code>int64 lastLoginTime = 8;</code>
     * @return The lastLoginTime.
     */
    @java.lang.Override
    public long getLastLoginTime() {
      return lastLoginTime_;
    }
    /**
     * <code>int64 lastLoginTime = 8;</code>
     * @param value The lastLoginTime to set.
     * @return This builder for chaining.
     */
    public Builder setLastLoginTime(long value) {

      lastLoginTime_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int64 lastLoginTime = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastLoginTime() {
      bitField0_ = (bitField0_ & ~0x00000080);
      lastLoginTime_ = 0L;
      onChanged();
      return this;
    }

    private long createTime_ ;
    /**
     * <code>int64 createTime = 9;</code>
     * @return The createTime.
     */
    @java.lang.Override
    public long getCreateTime() {
      return createTime_;
    }
    /**
     * <code>int64 createTime = 9;</code>
     * @param value The createTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTime(long value) {

      createTime_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int64 createTime = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateTime() {
      bitField0_ = (bitField0_ & ~0x00000100);
      createTime_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PlayerData)
  }

  // @@protoc_insertion_point(class_scope:PlayerData)
  private static final com.muyi.proto.game.PlayerData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.muyi.proto.game.PlayerData();
  }

  public static com.muyi.proto.game.PlayerData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlayerData>
      PARSER = new com.google.protobuf.AbstractParser<PlayerData>() {
    @java.lang.Override
    public PlayerData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PlayerData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlayerData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.muyi.proto.game.PlayerData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

