// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game.proto
// Protobuf Java Version: 4.34.0

package com.muyi.proto.game;

@com.google.protobuf.Generated
public interface PlayerInfoReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PlayerInfoReq)
    com.google.protobuf.MessageOrBuilder {
}
